"""``python -m rytm_randomizer.cockpit`` — launch the WebSocket sidecar.

This entrypoint is what the Tauri shell (WS-H) spawns when the cockpit
window opens. It wires the default collaborators (a fresh
:class:`MockDeviceAdapter`, the on-disk :class:`ProfileRegistry`, a fresh
:class:`HistoryStore`) into a :class:`CockpitSession`, mints a per-launch
handshake token, builds the :class:`FastAPI` app via :func:`create_app`,
and hands the result to ``uvicorn.run`` on ``127.0.0.1:4317``.

The port is overridable via the ``RYTM_RAND_WS_PORT`` environment
variable so devs running two cockpits side-by-side don't collide on the
default. The host is always loopback — the cockpit sidecar is intended
for the local Tauri shell only; exposing it on a routable interface is
a deliberate operator decision deferred to a later release (the spec
calls this out under Phase 1 scope).

Why a token-on-disk handshake (and not "just bind loopback")
-----------------------------------------------------------

The previous boot path accepted ``ws://127.0.0.1:4317/ws`` from any
local process — and "any local process" includes a malicious browser
tab the operator opens while the cockpit is running. Same-origin policy
does NOT protect WebSockets: a foreign page can issue
``new WebSocket("ws://localhost:4317/ws")`` and drive every command
including ``send`` (when ``--arm``), ``wizard_save``, and
``export_profile_model``. See CODE_REVIEW.md PR 1 finding C1.

The fix is a per-launch HMAC token generated by :func:`main` via
:func:`secrets.token_urlsafe` and written to disk under
``RYTM_RAND_WS_TOKEN_FILE`` (mandatory for armed/production launches)
or, when unset, a default at ``~/.rytm-randomizer/cockpit-ws-token``
with mode ``0600`` on POSIX (best-effort on Windows — the platform's
ACL model does not map cleanly to POSIX permission bits). The Tauri
shell reads the same file and includes the token in the first WS frame.
A web tab that does not see that file cannot guess the 32-byte
URL-safe value within any tractable budget, so the cockpit's command
surface stops being a localhost remote-control hole.
"""

from __future__ import annotations

import importlib.util
import os
import secrets
import stat
import sys
from collections.abc import Callable
from datetime import datetime, timezone
from pathlib import Path
from typing import Final

import uvicorn
from fastapi import FastAPI

from ..observability.logging import get_logger
from .data import PadState, Snapshot, new_ulid
from .device import MockDeviceAdapter
from .device.connection import (
    ConnectionManager,
    ConnectionState,
    NullPortEnumerator,
    PortEnumerator,
    ProviderPortEnumerator,
    set_active_connection_manager,
)
from .device.midi_monitor import MidiInputOpener, MidiMonitorSupervisor
from .history import HistoryStore
from .library import LibraryStore, default_captures_dir, default_library_dir
from .profiles import ProfileRegistry, default_profiles_dir
from .ws.handlers import build_armed_watchdog, build_connection_changed
from .ws.server import ConnectionRegistry, create_app
from .ws.session import CockpitSession

_logger = get_logger(__name__)
"""Module logger for the cockpit sidecar entrypoint (token provisioning,
port resolution, uvicorn boot). Bound here so PR O6 (arch tests on
hot-path loggers) can wire its structured events without touching this
file's imports. See ``OBSERVABILITY_REVIEW.md`` Phase 5."""

_DEFAULT_HOST = "127.0.0.1"
"""Loopback only — never expose the cockpit to a routable interface in Phase 1."""

_DEFAULT_PORT = 4317
"""The default port the Tauri shell knows to dial. Override via RYTM_RAND_WS_PORT."""

_PORT_ENV_VAR = "RYTM_RAND_WS_PORT"
"""Environment variable the Tauri shell may set when starting multiple cockpits."""

_TOKEN_FILE_ENV_VAR: Final[str] = (
    "RYTM_RAND_WS_TOKEN_FILE"  # noqa: S105 — env var name, not a secret value
)
"""Override for where the handshake token file is written.

When set, ``main()`` writes the freshly-minted token to this path
verbatim — production / Tauri-spawned launches use it to hand the path
to the shell so the shell can read the token on its side.

When unset, ``main()`` falls back to
``~/.rytm-randomizer/cockpit-ws-token`` (default dev path) and prints
the token to stdout so an interactive developer can copy it without
hunting through the filesystem.
"""

_TOKEN_BYTES: Final[int] = 32
"""URL-safe entropy width for :func:`secrets.token_urlsafe` — 32 bytes ≈ 43 chars.

Wider than the cookies most systems rely on, narrow enough to fit on a
single Tauri argv. Matches the recipe in CODE_REVIEW.md PR 1.
"""

_DEFAULT_TOKEN_REL_DIR: Final[Path] = Path(".rytm-randomizer")
"""Default directory (under ``$HOME``) for the dev-mode token file."""

_DEFAULT_TOKEN_FILE_NAME: Final[str] = (
    "cockpit-ws-token"  # noqa: S105 — filename, not a secret value
)
"""File name for the dev-mode token file inside :data:`_DEFAULT_TOKEN_REL_DIR`."""

_DEFAULT_DEVICE = "analog_rytm_mk2"
"""Identifier the bootstrap snapshot wears — matches the production hardware."""

_DEFAULT_BPM = 124.0
"""Reasonable bpm placeholder for a fresh session; the user will set their own."""


def _default_initial_snapshot() -> Snapshot:
    """Build a clean, deterministic 12-pad starting snapshot for the mock adapter.

    The exact parameter values don't matter for protocol correctness —
    they're a benign placeholder so the cockpit has *something* to render
    when the user opens the window for the first time. A real session
    overwrites them on the first SEND.
    """

    default_params = {
        # Synth / machine row, named after the operator-facing Overbridge controls.
        "tun": 64,
        "swt": 96,
        "snap": 28,
        "dec": 80,
        "wave": 1,
        "hold": 32,
        "tick": 72,
        "lev": 110,
        # Sample row.
        "sample_tune": 64,
        "sample_fine": 64,
        "sample_bit": 0,
        "sample_slot": 0,
        "sample_start": 0,
        "sample_end": 120,
        "sample_loop": 0,
        "sample_level": 100,
        # Filter envelope and multimode filter.
        "filter_attack": 0,
        "filter_decay": 64,
        "filter_sustain": 0,
        "filter_release": 64,
        "flt": 64,
        "filter_resonance": 24,
        "filter_env": 64,
        # Amp envelope / mixer sends.
        "amp_attack": 0,
        "amp_hold": 32,
        "amp_decay": 75,
        "pan": 64,
        "accent": 32,
        "overdrive": 32,
        "delay": 0,
        "reverb": 0,
        # LFO row.
        "lfo_speed": 48,
        "lfo_depth": 0,
        "lfo_phase": 0,
        "lfo_fade": 0,
        "lfo_mult": 16,
        "lfo_destination": 0,
    }
    pads = tuple(
        PadState(
            pad_id=pad_id,
            machine=machine,
            params=default_params,
        )
        for pad_id, machine in (
            (1, "BD Hard"),
            (2, "SD Classic"),
            (3, "CH Closed"),
            (4, "OH Open"),
            (5, "BT Rim"),
            (6, "LT Low"),
            (7, "MT Mid"),
            (8, "HT High"),
            (9, "CP Clap"),
            (10, "RS Riser"),
            (11, "SY Raw"),
            (12, "BD Acoustic"),
        )
    )
    return Snapshot(
        snapshot_id=new_ulid(),
        device=_DEFAULT_DEVICE,
        captured_at=datetime.now(timezone.utc),
        pads=pads,
        scene_slot=None,
        bpm=_DEFAULT_BPM,
    )


def _resolve_port() -> int:
    """Pick the port to bind to: ``RYTM_RAND_WS_PORT`` overrides the default."""

    raw = os.environ.get(_PORT_ENV_VAR)
    if raw is None:
        return _DEFAULT_PORT
    return int(raw)


def _resolve_token_path() -> Path:
    """Return the absolute path the per-launch token is written to.

    Honours :data:`_TOKEN_FILE_ENV_VAR` when set (the production /
    Tauri-spawned path). Falls back to
    ``$HOME/.rytm-randomizer/cockpit-ws-token`` for interactive dev runs
    so a freshly-cloned repo "just works" without an env-var dance.
    """

    raw = os.environ.get(_TOKEN_FILE_ENV_VAR)
    if raw:
        return Path(raw).expanduser().absolute()
    return (Path.home() / _DEFAULT_TOKEN_REL_DIR / _DEFAULT_TOKEN_FILE_NAME).absolute()


def _write_token_file(path: Path, token: str) -> None:
    """Write the token to ``path`` with mode ``0600`` (best-effort on Windows).

    The parent directory is created on demand so the dev default path
    works on a fresh checkout. ``chmod(0o600)`` is a best-effort owner-
    only restriction — POSIX honours it; Windows quietly succeeds but
    the actual ACL is dictated by the parent directory and is generally
    already user-only under ``$HOME``. We do NOT propagate ``OSError``
    from ``chmod`` because a partially-restricted file is still better
    than refusing to launch.
    """

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(token, encoding="utf-8")
    try:
        path.chmod(stat.S_IRUSR | stat.S_IWUSR)  # 0o600
    except OSError:
        # Windows / certain filesystems may reject the bit-precise mode.
        # The dev default lives under $HOME, which is already user-private.
        pass


def _provision_token() -> str:
    """Mint a fresh per-launch token, persist it, and return it.

    Always generates a brand-new token — the file from a previous launch
    is overwritten so a stale token cannot survive across cockpit
    restarts. When :data:`_TOKEN_FILE_ENV_VAR` is unset (interactive dev
    run) the token is also echoed to stdout so the developer can read it
    without opening the file.
    """

    token = secrets.token_urlsafe(_TOKEN_BYTES)
    path = _resolve_token_path()
    _write_token_file(path, token)
    if _TOKEN_FILE_ENV_VAR not in os.environ:
        # Dev path: print so an interactive operator can copy it without
        # opening the file. The stdout pipe is the spawning shell's, not
        # the cockpit's wire, so this does not leak onto WS.
        print(f"[cockpit] WS token: {token}", file=sys.stdout, flush=True)
    return token


def build_session() -> CockpitSession:
    """Compose the default cockpit session — mock device, on-disk profiles, empty history."""

    initial_snapshot = _default_initial_snapshot()
    device = MockDeviceAdapter(initial=initial_snapshot)
    history_store = HistoryStore()
    history_store.initial(device.capture_snapshot())
    return CockpitSession(
        profile_registry=ProfileRegistry(default_profiles_dir()),
        history_store=history_store,
        device=device,
    )


def _build_port_enumerator() -> PortEnumerator:
    """Pick the passive port enumerator for this host.

    When ``mido`` is importable, the real enumeration-only facade over
    :class:`~rytm_randomizer.mido_provider.MidoMidiPortProvider` is used
    — enumeration ONLY; nothing reachable through the facade can open a
    port, and ``mido`` itself stays lazily imported inside the
    provider's methods. When ``mido`` is absent (a bare checkout without
    the hardware extra), the :class:`NullPortEnumerator` keeps the
    cockpit booting with the connection phase pinned at ``searching``.

    ``find_spec`` only *locates* the module — it never imports it, so
    the no-import-time-mido invariant
    (``tests/architecture/test_no_side_effects.py``) holds either way.
    """

    if importlib.util.find_spec("mido") is None:
        return NullPortEnumerator()
    # Imported lazily so merely importing ``cockpit.__main__`` (e.g. the
    # architecture suite's per-module import scan) never pulls the
    # real-MIDI boundary module until a launch actually happens.
    from ..mido_provider import build_mido_midi_port_provider  # noqa: PLC0415

    return ProviderPortEnumerator(build_mido_midi_port_provider())


def _build_input_opener() -> MidiInputOpener | None:
    """Pick the passive input opener for the live MIDI monitor.

    ``None`` when ``mido`` is absent — the monitor supervisor is then
    simply not wired and the cockpit runs without the ``midi_activity``
    stream (byte-identical to the pre-Wave-4 wire surface). Opening
    inputs is passive per the Live-but-Passive rule; the returned
    provider surface exposes ``open_input`` only through the monitor's
    :class:`~rytm_randomizer.cockpit.device.midi_monitor.MidiInputOpener`
    Protocol.
    """

    if importlib.util.find_spec("mido") is None:
        return None
    from ..mido_provider import build_mido_midi_port_provider  # noqa: PLC0415

    return build_mido_midi_port_provider()


def _connection_event_broadcaster(
    registry: ConnectionRegistry,
) -> Callable[[ConnectionState], None]:
    """Adapt a ConnectionRegistry into a ConnectionManager ``on_change``.

    Every observed diff becomes one ``connection_changed`` event fanned
    out to every live WebSocket client. ``broadcast_event`` is
    non-blocking and thread-safe, so the callback is safe to fire from
    the manager's poll loop on the serving event loop.
    """

    def _broadcast(state: ConnectionState) -> None:
        registry.broadcast_event(build_connection_changed(state))

    return _broadcast


def _install_connection_manager_lifecycle(app: FastAPI, manager: ConnectionManager) -> None:
    """Start/stop the manager's poll loop with the app's lifecycle.

    Registered as FastAPI ``startup`` / ``shutdown`` handlers so the
    poll task is created on uvicorn's serving event loop — the same
    loop the per-connection outbound queues capture, which keeps the
    broadcast fan-out loop-safe.
    """

    # Starlette >= 1.x dropped ``app.add_event_handler``; the router-level
    # registration is the stable surface across the pinned FastAPI line.
    app.router.add_event_handler("startup", manager.start)
    app.router.add_event_handler("shutdown", manager.stop)


def main() -> None:
    """Mint the handshake token, build the app, run uvicorn on the resolved port."""

    session = build_session()
    # Wave 4: the injected kit/sound library (JSON records under the
    # platform config dir; importer reads ./captures). Injected on the
    # session — the store module itself keeps zero module-level state.
    session.library_store = LibraryStore(
        default_library_dir(),
        captures_dir=default_captures_dir(),
    )
    token = _provision_token()
    connection_registry = ConnectionRegistry()
    manager = ConnectionManager(
        _build_port_enumerator(),
        on_change=_connection_event_broadcaster(connection_registry),
        # Wave 4: enumeration faults land in the session's bounded error
        # journal so the diagnostics command can replay them.
        journal=session.error_journal,
    )
    set_active_connection_manager(manager)
    # Wave 4: device gone while armed -> auto-disarm + fault signal
    # (never auto-re-arm — the operator must arm explicitly again).
    manager.add_notify_hook(build_armed_watchdog(session, connection_registry.broadcast_event))
    app = create_app(session, token=token, connection_registry=connection_registry)
    _install_connection_manager_lifecycle(app, manager)
    # Wave 4: passive live MIDI input stream — one monitor follows the
    # selected Elektron input and pushes coalesced ``midi_activity``
    # batches to every client. Only wired when ``mido`` is importable.
    input_opener = _build_input_opener()
    if input_opener is not None:
        supervisor = MidiMonitorSupervisor(
            input_opener,
            broadcast=connection_registry.broadcast_event,
        )
        manager.add_notify_hook(supervisor.notify)
        app.router.add_event_handler("shutdown", supervisor.aclose)
    uvicorn.run(app, host=_DEFAULT_HOST, port=_resolve_port())


if __name__ == "__main__":  # pragma: no cover - exercised via ``python -m``
    main()
