import type { LiveGuiPerformanceConsoleModelDict } from '../types/live_gui_protocol';
import { DEFAULT_STYLE_CRATE_REHEARSAL_DECK } from './styleCrateQueueModel';

const controllerBrainTemplatePageCards = [
  {
    page_key: 'global-brain',
    page_label: 'Global Brain',
    page_index: 1,
    row_count: 16,
    first_slot: 1,
    last_slot: 16,
  },
  {
    page_key: 'rytm-pads-1-4',
    page_label: 'Rytm Pads 1-4',
    page_index: 2,
    row_count: 16,
    first_slot: 1,
    last_slot: 16,
  },
  {
    page_key: 'rytm-pads-5-8',
    page_label: 'Rytm Pads 5-8',
    page_index: 3,
    row_count: 16,
    first_slot: 1,
    last_slot: 16,
  },
  {
    page_key: 'rytm-pads-9-12',
    page_label: 'Rytm Pads 9-12',
    page_index: 4,
    row_count: 16,
    first_slot: 1,
    last_slot: 16,
  },
  {
    page_key: 'analog-four-tracks',
    page_label: 'Analog Four Tracks',
    page_index: 5,
    row_count: 16,
    first_slot: 1,
    last_slot: 16,
  },
  {
    page_key: 'style-crates-queue',
    page_label: 'Style Crates / Queue',
    page_index: 6,
    row_count: 16,
    first_slot: 1,
    last_slot: 16,
  },
  {
    page_key: 'snapshot-recovery-journal',
    page_label: 'Snapshot Recovery / Journal',
    page_index: 7,
    row_count: 16,
    first_slot: 1,
    last_slot: 16,
  },
] as const;

const controllerBrainIntentForSlot = (pageKey: string, slot: number): string => {
  if (pageKey === 'global-brain' && slot === 1) return 'global.preview_depth';
  if (pageKey === 'global-brain' && slot === 7) return 'macro.industrial';
  if (pageKey === 'rytm-pads-5-8' && slot === 1) return 'rytm.pad5.source_amount';
  if (pageKey === 'rytm-pads-5-8' && slot === 5) return 'rytm.pad6.source_amount';
  if (pageKey === 'rytm-pads-9-12' && slot === 13) return 'rytm.pad12.source_amount';
  if (pageKey === 'analog-four-tracks' && slot === 1) return 'a4.track1.macro_depth';
  if (pageKey === 'style-crates-queue' && slot === 2) return 'crate.dark_hypnotic';
  if (pageKey === 'style-crates-queue' && slot === 10) return 'queue.next_1';
  if (pageKey === 'snapshot-recovery-journal' && slot === 16) return 'snapshot.panic_home';
  return `${pageKey}.slot${slot}`;
};

const controllerBrainTemplateRows = controllerBrainTemplatePageCards.flatMap((page) =>
  Array.from({ length: page.row_count }, (_, index) => {
    const slot = index + 1;
    const intentKey = controllerBrainIntentForSlot(page.page_key, slot);
    return {
      assignment_key: `${page.page_key}:${String(slot).padStart(2, '0')}`,
      page_key: page.page_key,
      page_label: page.page_label,
      page_index: page.page_index,
      slot,
      label: `Encoder ${slot}`,
      target_device: intentKey.startsWith('a4.') ? 'analog_four_mk2' : 'cockpit',
      target_scope: intentKey,
      intent_key: intentKey,
      action: 'stage-intent',
      lane: intentKey.includes('source') ? 'src' : 'control',
      safety_tier: 'passive',
      recovery_action: intentKey === 'snapshot.panic_home' ? 'captured-anchor' : 'review',
      operator_note: 'Demo controller-brain row for passive Cockpit rendering.',
    };
  }),
);

const controllerBrainGestureOutcomes = [
  ['global-brain:01', 'global-brain', 1, 'turn clockwise', 12, 'global.preview_depth'],
  ['global-brain:07', 'global-brain', 7, 'press', 0, 'macro.industrial'],
  ['rytm-pads-5-8:01', 'rytm-pads-5-8', 1, 'turn clockwise', 9, 'rytm.pad5.source_amount'],
  ['rytm-pads-5-8:05', 'rytm-pads-5-8', 5, 'turn clockwise', 14, 'rytm.pad6.source_amount'],
  [
    'rytm-pads-9-12:13',
    'rytm-pads-9-12',
    13,
    'turn counterclockwise',
    -7,
    'rytm.pad12.source_amount',
  ],
  [
    'analog-four-tracks:01',
    'analog-four-tracks',
    1,
    'turn clockwise',
    10,
    'a4.track1.macro_depth',
  ],
  ['style-crates-queue:02', 'style-crates-queue', 2, 'press', 0, 'crate.dark_hypnotic'],
  ['style-crates-queue:10', 'style-crates-queue', 10, 'press', 0, 'queue.next_1'],
  [
    'snapshot-recovery-journal:16',
    'snapshot-recovery-journal',
    16,
    'press and hold',
    0,
    'snapshot.panic_home',
  ],
].map(([assignmentKey, pageKey, slot, gesture, valueDelta, intentKey], index) => ({
  step: index + 1,
  assignment_key: String(assignmentKey),
  page_key: String(pageKey),
  slot: Number(slot),
  gesture: String(gesture),
  value_delta: Number(valueDelta),
  resolved_intent_key: String(intentKey),
  resolved_action: 'stage-intent',
  resolved_target_device: String(intentKey).startsWith('a4.') ? 'analog_four_mk2' : 'cockpit',
  resolved_target_scope: String(intentKey),
  lane: String(intentKey).includes('source') ? 'src' : 'control',
  safety_tier: 'passive',
  recovery_action: intentKey === 'snapshot.panic_home' ? 'captured-anchor' : 'review',
  status: 'passive-intent-staged',
  operator_goal: 'Render the passive controller-brain rehearsal in Cockpit.',
  notes: 'Demo outcome; no controller input, WebSocket dispatch, or MIDI send.',
}));

export const performanceConsoleDemoModel: LiveGuiPerformanceConsoleModelDict = {
  console_version: 'live-gui-performance-console-v1',
  source_module: 'desktop.web.cockpit.performanceConsoleDemoModel',
  console_id: 'console-demo',
  session_label: 'Warehouse arc',
  console_status: 'mock-safe',
  hardware_mode: 'passive',
  device_inventory: {
    model_version: 'live-gui-device-inventory-v1',
    device_count: 2,
    cards: [
      {
        device_id: 'analog_rytm_mk2',
        display_name: 'Elektron Analog Rytm MKII',
        order: 1,
        track_count: 12,
        default_midi_channel_label: '1-12',
        sysex_manufacturer_id_hex: '00 20 3c',
        role_summary: '12-pad drum and sample performance surface',
        port_state: 'closed',
        hardware_state: 'disarmed',
        mock_state: 'mock-safe',
        can_open_port: false,
        can_arm_hardware: false,
        capability_badges: ['12 pads', 'snapshot-safe'],
        passive: true,
      },
      {
        device_id: 'analog_four_mk2',
        display_name: 'Elektron Analog Four MKII',
        order: 2,
        track_count: 4,
        default_midi_channel_label: '1-4',
        sysex_manufacturer_id_hex: '00 20 3c',
        role_summary: '4-track synth performance surface',
        port_state: 'closed',
        hardware_state: 'disarmed',
        mock_state: 'review-only',
        can_open_port: false,
        can_arm_hardware: false,
        capability_badges: ['4 synth tracks', 'macro review'],
        passive: true,
      },
    ],
    blocked_actions: ['open_midi_port_without_arm'],
    safety: ['passive/read-only'],
  },
  rytm_pad_surface: {
    model_version: 'live-gui-12-pad-surface-v1',
    pad_count: 12,
    active_pad_count: 12,
    planned_pad_count: 0,
    cards: Array.from({ length: 12 }, (_, index) => ({
      pad: index + 1,
      track_code: index + 1 === 11 ? 'SY' : `T${index + 1}`,
      label: index + 1 === 11 ? 'SY Raw' : `Pad ${index + 1}`,
      surface_state: 'active',
      ui_enabled: true,
      ui_locked: false,
      lock_reason: '',
      default_role: index + 1 >= 6 && index + 1 <= 8 ? 'tom' : 'performance',
      default_machine_label: index + 1 === 11 ? 'SY Raw' : 'Snapshot machine',
      legal_machine_count: 4,
      snapshot_mutable_machine_count: 4,
      selectable_only_machine_count: 0,
      primary_machine_labels: ['Snapshot machine'],
    })),
    blocked_actions: ['send_midi'],
    safety: ['no MIDI sending'],
  },
  rytm_lane_policy_matrix: {
    matrix_version: 'performance-console-rytm-lane-policy-matrix-v1',
    matrix_id: 'rytm-oxi-lane-policy-matrix',
    matrix_status: 'passive-ready',
    source_report: 'oxi-live-macro-catalog-report',
    macro_count: 6,
    pad_groups: [
      {
        group_key: 'reserved-src-fx',
        pads: [5, 9, 10, 11],
        summary: 'SRC-first reserved percussion pads',
        lane_policy: 'SRC primary; filter=off; lfo=off; AMP limited to overdrive/delay/reverb',
        operator_note:
          'Pads 5, 9, 10, and 11 keep source movement as the main musical control.',
      },
      {
        group_key: 'tom-source',
        pads: [6, 7, 8],
        summary: 'tom/source movement pads',
        lane_policy: 'SRC primary; filter=micro/light; lfo=off; AMP limited to overdrive/delay/reverb',
        operator_note:
          'Pads 6-8 can move harder on tom source controls while filter stays light.',
      },
      {
        group_key: 'pad-12-supported',
        pads: [12],
        summary: 'product-supported expansion pad',
        lane_policy:
          'Pad 12 remains eligible for product users even when Jose does not use it.',
        operator_note: 'Keep Pad 12 visible as supported, but do not make it a live dependency.',
      },
    ],
    macro_rows: [
      {
        macro_key: 'kit-core',
        order: 1,
        label: 'Kit Core',
        style_crate: 'Core Tools',
        risk_label: 'live-safe',
        energy: 5,
        risk: 2,
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        locked_pads: [1],
        lane_policy_summary: 'fx=micro, lfo=off',
        pad_policy_cards: {
          '5': {
            amount: 'normal',
            density: 'high',
            bias: null,
            lane_policies: { filter: 'off', lfo: 'off' },
            section_family_allowlists: { AMP: ['delay', 'overdrive', 'reverb'] },
          },
          '6': {
            amount: 'wide',
            density: 'full',
            bias: 'tighter',
            lane_policies: { filter: 'micro', lfo: 'off' },
            section_family_allowlists: { AMP: ['delay', 'overdrive', 'reverb'] },
          },
        },
        recovery_action: 'home',
        summary: "Full-kit live-safe discovery with Jose's pad 5-11 lane discipline.",
      },
      {
        macro_key: 'hard-groove',
        order: 2,
        label: 'Hard Groove',
        style_crate: 'Hard Groove',
        risk_label: 'live-safe',
        energy: 7,
        risk: 3,
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        locked_pads: [1],
        lane_policy_summary: 'fx=micro, lfo=off',
        pad_policy_cards: {
          '5': {
            amount: 'normal',
            density: 'high',
            bias: 'tighter',
            lane_policies: { filter: 'off', lfo: 'off' },
            section_family_allowlists: { AMP: ['delay', 'overdrive', 'reverb'] },
          },
          '6': {
            amount: 'wide',
            density: 'full',
            bias: 'tighter',
            lane_policies: { filter: 'micro', lfo: 'off' },
            section_family_allowlists: { AMP: ['delay', 'overdrive', 'reverb'] },
          },
          '9': {
            amount: 'normal',
            density: 'high',
            bias: 'brighter',
            lane_policies: { filter: 'off', lfo: 'off' },
            section_family_allowlists: { AMP: ['delay', 'overdrive', 'reverb'] },
          },
          '12': {
            amount: 'normal',
            density: 'medium',
            bias: 'neutral',
            lane_policies: {},
            section_family_allowlists: { AMP: ['delay', 'overdrive', 'reverb'] },
          },
        },
        recovery_action: 'home',
        summary: 'Dry pressure macro for OXI patterns that already carry the groove.',
      },
      {
        macro_key: 'industrial',
        order: 3,
        label: 'Industrial',
        style_crate: 'Industrial Warehouse',
        risk_label: 'edge',
        energy: 8,
        risk: 5,
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        locked_pads: [1],
        lane_policy_summary: 'fx=micro, lfo=off',
        pad_policy_cards: {},
        recovery_action: 'home',
        summary: 'Metallic pressure and controlled grit without releasing the kick anchor.',
      },
      {
        macro_key: 'dub-pressure',
        order: 4,
        label: 'Dub Pressure',
        style_crate: 'Dub Pressure',
        risk_label: 'live-safe',
        energy: 6,
        risk: 3,
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        locked_pads: [1],
        lane_policy_summary: 'fx=normal, lfo=off',
        pad_policy_cards: {},
        recovery_action: 'home',
        summary: 'Darker pressure with more delay/reverb influence and small filter motion.',
      },
      {
        macro_key: 'transition',
        order: 5,
        label: 'Transition',
        style_crate: 'Transition / Build',
        risk_label: 'edge',
        energy: 7,
        risk: 5,
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        locked_pads: [1],
        lane_policy_summary: 'fx=normal, lfo=micro',
        pad_policy_cards: {},
        recovery_action: 'home',
        summary: 'Set-section movement with obvious recovery through home.',
      },
      {
        macro_key: 'home',
        order: 6,
        label: 'Home',
        style_crate: 'Home / Reset',
        risk_label: 'live-safe',
        energy: 1,
        risk: 1,
        affected_pads: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        locked_pads: [],
        lane_policy_summary: 'none',
        pad_policy_cards: {},
        recovery_action: 'home',
        summary: 'Return the current staged plan to the captured anchor.',
      },
    ],
    blocked_actions: [
      'dispatch Rytm lane policy from Cockpit console',
      'send Rytm lane policy from Cockpit console',
    ],
    safety_lines: [
      'Rytm lane policy matrix is declarative only',
      'Cockpit shows macro policy before the armed snapshot shell applies anything',
      'no MIDI sending',
      'no port opening',
    ],
    replay_commands: ['python -m rytm_randomizer.cli oxi-live-macro-catalog-report'],
  },
  performance_flow: {
    model_version: 'live-gui-performance-flow-model-v1',
    source_module: 'reports.live_gui_performance_flow_model',
    flow_id: 'oxi-rytm-a4-performance-flow',
    flow_status: 'mock-safe',
    current_step_key: 'kit-core',
    steps: [
      {
        key: 'capture-anchor',
        order: 1,
        label: 'Capture Anchor',
        phase: 'setup',
        rytm_command: 'kit / resnapshot',
        analog_four_action: 'soft-capture reference',
        send_policy: 'receive-only',
        recovery_action: 'Z + send',
        status: 'safe',
      },
      {
        key: 'kit-core',
        order: 2,
        label: 'Kit Core',
        phase: 'foundation',
        rytm_command: 'kit-core',
        analog_four_action: 'review warehouse macro',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        status: 'staged',
      },
    ],
    analog_four_readiness: {
      readiness: 'review-ready',
      command: 'python -m rytm_randomizer.cli analog-four-oxi-macro-readiness-report',
      summary: 'A4 macro rows are review-ready; full macro SEND remains blocked.',
      blocked_active_actions: ['a4_outbound_macro_send'],
    },
    analog_four_set_plan: {
      set_name: 'warehouse-arc',
      current_macro: 'home',
      up_next_macros: ['hard-groove', 'dub-pressure', 'industrial-transition'],
      step_count: 4,
      replay_command: 'python -m rytm_randomizer.cli analog-four-oxi-macro-set-planner-report --json',
      summary: 'warehouse-arc stages A4 macro moves for review.',
      blocked_active_actions: ['A4 full macro SEND'],
    },
    blocked_actions: ['a4_outbound_macro_send'],
    safety_lines: ['passive/read-only'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-performance-flow-model-report --json'],
  },
  macro_action_deck: {
    deck_version: 'performance-console-macro-action-deck-v1',
    deck_id: 'rytm-live-macro-actions',
    deck_status: 'passive-ready',
    current_macro_key: 'kit-core',
    cards: [
      {
        macro_key: 'kit-core',
        order: 1,
        label: 'Kit Core',
        shell_command: 'kit-core',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        risk_label: 'safe',
        affected_pads: [1, 2, 3, 4],
        pad_count: 4,
        status: 'staged',
        hardware_action_state: 'blocked',
        hardware_send_enabled: false,
        dry_run_only: true,
        operator_hint: 'Type kit-core in the armed shell, inspect changes, send manually, and recover with home.',
        test_id: 'macro-action-kit-core',
      },
      {
        macro_key: 'hard-groove',
        order: 2,
        label: 'Hard Groove',
        shell_command: 'hard-groove',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        risk_label: 'safe',
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        pad_count: 11,
        status: 'staged',
        hardware_action_state: 'blocked',
        hardware_send_enabled: false,
        dry_run_only: true,
        operator_hint:
          'Type hard-groove in the armed shell, inspect changes, send manually, and recover with home.',
        test_id: 'macro-action-hard-groove',
      },
      {
        macro_key: 'industrial',
        order: 3,
        label: 'Industrial',
        shell_command: 'industrial',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        risk_label: 'review',
        affected_pads: [2, 3, 4, 6, 7, 8, 11, 12],
        pad_count: 8,
        status: 'review',
        hardware_action_state: 'blocked',
        hardware_send_enabled: false,
        dry_run_only: true,
        operator_hint:
          'Type industrial in the armed shell, inspect changes, send manually, and recover with home.',
        test_id: 'macro-action-industrial',
      },
    ],
    blocked_actions: ['fire macro from Cockpit console', 'prepare hardware send from Cockpit macro action'],
    safety_lines: [
      'macro action cards are declarative only',
      'operators still use the armed snapshot shell for real sends',
      'all Cockpit macro fire controls stay disabled',
    ],
    replay_commands: [
      'python -m rytm_randomizer.cli oxi-live-macro-catalog-report',
      'python -m rytm_randomizer.cli live-gui-performance-flow-model-report --json',
    ],
  },
  rehearsal_board: {
    board_version: 'performance-console-rehearsal-board-v1',
    board_id: 'oxi-live-rehearsal-board',
    board_status: 'passive-ready',
    title: 'OXI Live Rehearsal Board',
    launch_command:
      'python -m rytm_randomizer.app --arm --rytm-live-snapshot-shell --confirm-rytm-snapshot-shell-send',
    studio_workflow: [
      'Capture the current Rytm kit with KIT SysEx before changing anything.',
      'Use kit or resnapshot whenever the hardware kit changes.',
      'Run changes before send or go.',
      'Keep OXI handling notes, triggers, mutes, and pattern motion.',
    ],
    chapters: [
      {
        order: 1,
        name: 'capture-anchor',
        label: 'Capture Anchor',
        rytm_command: 'kit/resnapshot',
        macro_sequence: ['kit-core'],
        a4_review_action: 'hold-current-a4-patch',
        operator_intent: 'Capture the current Rytm kit before any set movement.',
        recovery_action: 'captured anchor',
      },
      {
        order: 2,
        name: 'establish-groove',
        label: 'Establish Groove',
        rytm_command: 'macro hard-groove',
        macro_sequence: ['kit-core', 'hard-groove'],
        a4_review_action: 'review hard-groove A4 macro',
        operator_intent: 'Let OXI keep the groove while Rytm tightens source-first pressure.',
        recovery_action: 'home',
      },
      {
        order: 3,
        name: 'pressure-build',
        label: 'Pressure Build',
        rytm_command: 'macro industrial',
        macro_sequence: ['hard-groove', 'industrial'],
        a4_review_action: 'review industrial-transition A4 macro',
        operator_intent: 'Raise grit, metal, and energy without releasing the kick anchor.',
        recovery_action: 'home',
      },
    ],
    operator_cues: [
      {
        chapter_name: 'capture-anchor',
        label: 'Capture Anchor',
        oxi_action: 'hold or prepare the first pattern',
        rytm_stage_command: 'kit/resnapshot',
        inspect_command: 'status',
        fire_command: 'no send',
        recovery_command: 'captured anchor',
        a4_action: 'hold-current-a4-patch',
        expected_result: 'current Rytm kit becomes the safe anchor before the set moves',
        blocked_action: 'no mutation before anchor capture',
      },
      {
        chapter_name: 'establish-groove',
        label: 'Establish Groove',
        oxi_action: 'keep groove, triggers, mutes, and pattern motion running',
        rytm_stage_command: 'macro hard-groove',
        inspect_command: 'changes',
        fire_command: 'send or go',
        recovery_command: 'home + send or Z + send',
        a4_action: 'review hard-groove A4 macro',
        expected_result: 'tight source-first Rytm pressure over the OXI pattern',
        blocked_action: 'no unattended sends',
      },
    ],
    pad_lane_checks: [
      {
        pads: [5, 9, 10, 11],
        summary: 'Pads 5, 9, 10, 11: SRC stays important',
        expected_motion:
          'source movement plus overdrive, delay, and reverb; filter/LFO remain restrained',
        warning: 'Flag any macro that forgets SRC or pushes filter/LFO movement too hard.',
      },
      {
        pads: [6, 7, 8],
        summary: 'Pads 6-8: tom/source movement',
        expected_motion: 'useful tom/source discovery with light filter movement and no LFO craziness',
        warning: 'Flag any XT/tom lane that loses its drum identity or gets too animated.',
      },
    ],
    macro_checkpoints: [
      {
        name: 'hard-groove',
        label: 'Hard Groove',
        risk_label: 'live-safe',
        recovery_action: 'home',
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        summary: 'Dry pressure macro for OXI patterns that already carry the groove.',
        checkpoints: ['capture anchor first', 'run changes before send', 'recover with home'],
      },
    ],
    hardware_validation_runway: [
      {
        name: 'rytm-kit-core-smoke',
        device: 'Analog Rytm MKII',
        operator_path: 'kit-core -> changes -> send -> go -> Z + send',
        validation_mode: 'operator-present armed Rytm shell',
        expected_evidence: 'full-kit macro sounds musical and returns to no parameter changes staged',
        safety_boundary: 'requires --arm and explicit shell send/go commands',
      },
      {
        name: 'a4-soft-capture',
        device: 'Analog Four MKII',
        operator_path: '--arm --a4-soft-capture',
        validation_mode: 'input-only',
        expected_evidence: 'tracks 1-4 emit known Appendix D labels for moved controls',
        safety_boundary: 'opens A4 input only; no output and no MIDI send',
      },
    ],
    promotion_criteria: [
      {
        name: 'a4-input-label-coverage',
        device: 'Analog Four MKII',
        current_status: 'blocked',
        required_evidence: 'known labels for moved controls on tracks 1-4',
        promotes_to: 'A4 macro readiness review',
        safety_note: 'input-only evidence comes before any outbound A4 macro path',
      },
    ],
    recovery_checks: [
      'home then send returns to the captured safe kit.',
      'Z then send is still the emergency return-to-anchor path.',
    ],
    next_hardware_validations: [
      'Rytm full-kit macro smoke test from a fresh current-kit capture',
      'A4 input-only soft-capture pass before any outbound macro promotion',
    ],
    replay_commands: [
      {
        name: 'read-strategy',
        execution_mode: 'passive-cli',
        command: 'python -m rytm_randomizer.cli oxi-live-set-strategy-report',
        purpose: 'Read the operator strategy before a rehearsal.',
        expected_observation: 'report prints OXI roles, chapters, pad policies, and safety notes',
        opens_ports: false,
        sends_midi: 'never',
        safety_note: 'metadata-only report',
      },
      {
        name: 'start-rytm-live-shell',
        execution_mode: 'armed-operator-shell',
        command:
          'python -m rytm_randomizer.app --arm --rytm-live-snapshot-shell --confirm-rytm-snapshot-shell-send',
        purpose: 'Capture the current Rytm kit and enter the operator-present shell.',
        expected_observation: 'loaded kit name and fingerprint are visible',
        opens_ports: true,
        sends_midi: 'only after explicit in-shell send/go',
        safety_note: 'requires Jose present with hardware on',
      },
    ],
    blocked_actions: [
      'fire rehearsal cue from Cockpit console',
      'open MIDI port from rehearsal board',
      'send MIDI from rehearsal board',
      'promote A4 macro from rehearsal board',
    ],
    safety_lines: [
      'rehearsal board is declarative only',
      'launch command is shown for operator copy/review only',
      'real Rytm sends remain in the explicitly armed snapshot shell',
      'A4 outbound macro promotion remains blocked',
      'no MIDI sending',
    ],
  },
  controller_brain_panel: {
    panel_version: 'performance-console-controller-brain-panel-v1',
    panel_id: 'controller-brain-rehearsal-panel',
    panel_status: 'passive-ready',
    source_report: 'controller-brain-rehearsal-report',
    title: 'RytmRandomizer passive controller brain rehearsal report',
    profile_key: 'generic-16-encoder-performance',
    profile_label: 'Generic 16 Encoder Performance Controller',
    controller_family: 'generic-16-encoder',
    controller_layout: '7 pages x 16 controls',
    scenario_key: 'warehouse-controller-brain-rehearsal',
    scenario_label: 'Warehouse Controller Brain Rehearsal',
    scenario_summary:
      'Virtual 16-encoder rehearsal for Rytm, Analog Four, Style Crates, queue, and recovery intent.',
    template_row_count: 112,
    template_rows: controllerBrainTemplateRows,
    template_page_count: controllerBrainTemplatePageCards.length,
    template_page_cards: controllerBrainTemplatePageCards,
    gesture_count: controllerBrainGestureOutcomes.length,
    gesture_outcomes: controllerBrainGestureOutcomes,
    operator_notes: [
      'Treat the controller as an intent browser, not as a live MIDI input device.',
      'Use SRC-first Rytm pad controls for Pads 5-12 before broad filter or LFO moves.',
      'Keep Pad 12 available for users who want it, while allowing local lock/exclusion.',
      'Analog Four controls are staged as runway intent until a validated A4 hardware path exists.',
    ],
    blocked_actions: [
      'open MIDI controller input',
      'MIDI learn or raw CC capture',
      'send controller feedback',
      'dispatch Cockpit WebSocket commands',
      'open MIDI output',
      'arm hardware',
      'send hardware MIDI',
    ],
    safety_lines: [
      'passive/read-only',
      'controller-template rows only',
      'virtual encoder gestures only',
      'no MIDI controller input',
      'no MIDI learn or raw CC capture',
      'no WebSocket command dispatch',
      'no MIDI sending',
      'no port opening',
      'no hardware mutation',
      'no hardware required',
    ],
    replay_commands: [
      'python -m rytm_randomizer.cli controller-brain-mapping-report --json',
      'python -m rytm_randomizer.cli controller-brain-rehearsal-report --json',
    ],
  },
  analog_four_review_surface: {
    surface_version: 'performance-console-a4-review-surface-v1',
    surface_id: 'a4-oxi-macro-review-surface',
    surface_status: 'review-only',
    title: 'Analog Four Review Surface',
    set_name: 'warehouse-arc',
    step_count: 5,
    current_step: {
      order: 1,
      macro_name: 'home',
      macro_label: 'Home',
      summary: 'Return A4 movement to a known low-pressure anchor.',
      seed: 0,
      intensity: 2,
      energy: 2,
      readiness: 'review-ready',
      event_count: 8,
      ready_count: 8,
      review_count: 0,
      blocked_count: 0,
      validation_command: 'analog-four-oxi-macro-readiness-report home --seed 0 --intensity 2 --limit 4',
      recovery_action: 'reload saved A4 kit or return to home macro',
    },
    up_next: [
      {
        order: 2,
        macro_name: 'hard-groove',
        macro_label: 'Hard Groove',
        summary: 'Tighten synth pressure around the OXI groove without taking over the Rytm.',
        seed: 1,
        intensity: 5,
        energy: 5,
        readiness: 'review-ready',
        event_count: 20,
        ready_count: 20,
        review_count: 0,
        blocked_count: 0,
        validation_command:
          'analog-four-oxi-macro-readiness-report hard-groove --seed 1 --intensity 5 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
      {
        order: 3,
        macro_name: 'dub-pressure',
        macro_label: 'Dub Pressure',
        summary: 'Space and delay pressure for the middle of the warehouse arc.',
        seed: 2,
        intensity: 4,
        energy: 4,
        readiness: 'review-ready',
        event_count: 18,
        ready_count: 18,
        review_count: 0,
        blocked_count: 0,
        validation_command:
          'analog-four-oxi-macro-readiness-report dub-pressure --seed 2 --intensity 4 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
      {
        order: 4,
        macro_name: 'industrial-transition',
        macro_label: 'Industrial Transition',
        summary: 'Metallic transition motion while Rytm carries the drum identity.',
        seed: 3,
        intensity: 6,
        energy: 6,
        readiness: 'review-ready',
        event_count: 22,
        ready_count: 22,
        review_count: 0,
        blocked_count: 0,
        validation_command:
          'analog-four-oxi-macro-readiness-report industrial-transition --seed 3 --intensity 6 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
      {
        order: 5,
        macro_name: 'home',
        macro_label: 'Home',
        summary: 'Release synth pressure back to the safe home macro.',
        seed: 4,
        intensity: 2,
        energy: 2,
        readiness: 'review-ready',
        event_count: 8,
        ready_count: 8,
        review_count: 0,
        blocked_count: 0,
        validation_command: 'analog-four-oxi-macro-readiness-report home --seed 4 --intensity 2 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
    ],
    steps: [
      {
        order: 1,
        macro_name: 'home',
        macro_label: 'Home',
        summary: 'Return A4 movement to a known low-pressure anchor.',
        seed: 0,
        intensity: 2,
        energy: 2,
        readiness: 'review-ready',
        event_count: 8,
        ready_count: 8,
        review_count: 0,
        blocked_count: 0,
        validation_command: 'analog-four-oxi-macro-readiness-report home --seed 0 --intensity 2 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
      {
        order: 2,
        macro_name: 'hard-groove',
        macro_label: 'Hard Groove',
        summary: 'Tighten synth pressure around the OXI groove without taking over the Rytm.',
        seed: 1,
        intensity: 5,
        energy: 5,
        readiness: 'review-ready',
        event_count: 20,
        ready_count: 20,
        review_count: 0,
        blocked_count: 0,
        validation_command:
          'analog-four-oxi-macro-readiness-report hard-groove --seed 1 --intensity 5 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
      {
        order: 3,
        macro_name: 'dub-pressure',
        macro_label: 'Dub Pressure',
        summary: 'Space and delay pressure for the middle of the warehouse arc.',
        seed: 2,
        intensity: 4,
        energy: 4,
        readiness: 'review-ready',
        event_count: 18,
        ready_count: 18,
        review_count: 0,
        blocked_count: 0,
        validation_command:
          'analog-four-oxi-macro-readiness-report dub-pressure --seed 2 --intensity 4 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
      {
        order: 4,
        macro_name: 'industrial-transition',
        macro_label: 'Industrial Transition',
        summary: 'Metallic transition motion while Rytm carries the drum identity.',
        seed: 3,
        intensity: 6,
        energy: 6,
        readiness: 'review-ready',
        event_count: 22,
        ready_count: 22,
        review_count: 0,
        blocked_count: 0,
        validation_command:
          'analog-four-oxi-macro-readiness-report industrial-transition --seed 3 --intensity 6 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
      {
        order: 5,
        macro_name: 'home',
        macro_label: 'Home',
        summary: 'Release synth pressure back to the safe home macro.',
        seed: 4,
        intensity: 2,
        energy: 2,
        readiness: 'review-ready',
        event_count: 8,
        ready_count: 8,
        review_count: 0,
        blocked_count: 0,
        validation_command: 'analog-four-oxi-macro-readiness-report home --seed 4 --intensity 2 --limit 4',
        recovery_action: 'reload saved A4 kit or return to home macro',
      },
    ],
    review_focus: {
      macro_name: 'hard-groove',
      macro_label: 'Hard Groove',
      seed: 1,
      intensity: 5,
      energy: 5,
      readiness: 'review-ready',
      event_count: 20,
      ready_count: 20,
      review_count: 0,
      blocked_count: 0,
      shown_count: 4,
    },
    readiness_events: [
      {
        track: 1,
        role: 'bass',
        lane: 'filter',
        parameter: 'FLT Frequency',
        channel: 1,
        control: 74,
        value: 72,
        status: 'cc-ready',
        validation_command:
          'python -m rytm_randomizer.app --arm --a4-send-param --track 1 --parameter FLT Frequency --value 72',
        reason: 'manual-backed CC MSB row is available through --a4-send-param',
      },
      {
        track: 2,
        role: 'chord',
        lane: 'amp',
        parameter: 'AMP Overdrive',
        channel: 2,
        control: 81,
        value: 38,
        status: 'cc-ready',
        validation_command:
          'python -m rytm_randomizer.app --arm --a4-send-param --track 2 --parameter AMP Overdrive --value 38',
        reason: 'manual-backed CC MSB row is available through --a4-send-param',
      },
    ],
    preflight_command: 'python -m rytm_randomizer.app --arm --a4-soft-capture',
    validation_steps: [
      'Run the input-only A4 soft capture first.',
      'Review known and unknown controls before sending one row.',
      'Send one validation command while watching the A4 display.',
      'Repeat only rows that remain musical and reversible.',
    ],
    recovery_notes: [
      'Stop immediately if the A4 display shows ERR',
      'Do not run full A4 macro SEND from this report.',
      'Return the A4 kit manually or reload the saved kit before continuing.',
    ],
    promotion_gates: [
      'Every row maps to manual-backed CC metadata',
      'At least one operator-present validation pass is clean',
      'A recovery/stop procedure is documented.',
    ],
    replay_command: 'python -m rytm_randomizer.cli analog-four-oxi-macro-set-planner-report --json',
    readiness_replay_command:
      'python -m rytm_randomizer.cli analog-four-oxi-macro-readiness-report hard-groove --seed 1 --intensity 5 --limit 4 --json',
    opens_ports: false,
    sends_midi: false,
    hardware_required: false,
    blocked_actions: [
      'trigger A4 macro from Cockpit console',
      'open A4 output port from Cockpit console',
      'A4 full macro SEND',
      'A4 unattended macro playback',
    ],
    safety_lines: [
      'A4 review surface is declarative only',
      'A4 validation commands are shown for operator review only',
      'no MIDI sending',
      'no port opening',
      'A4 full macro SEND remains blocked',
    ],
  },
  style_queue: DEFAULT_STYLE_CRATE_REHEARSAL_DECK,
  analyzer_panel: {
    title: 'Analyzer (Post-Mutation Preview)',
    panel_model_version: 'live-gui-analyzer-panel-model-v1',
    panel_id: 'analyzer-empty',
    panel_status: 'empty',
    panel_mode: 'split',
    reference_label: 'No reference loaded',
    source_kind: 'none',
    confidence: 'none',
    bpm: 0,
    tempo_stability_percent: 0,
    waveform_bins: Array.from({ length: 8 }, (_, index) => ({
      index,
      label: `bin ${index + 1}`,
      value_percent: 0,
      status: 'empty',
    })),
    spectrum_bands: [
      { key: 'low', label: 'Low', low_hz: 20, high_hz: 120, value_percent: 0, status: 'empty' },
      { key: 'body', label: 'Body', low_hz: 120, high_hz: 350, value_percent: 0, status: 'empty' },
      { key: 'mid', label: 'Mid', low_hz: 350, high_hz: 2500, value_percent: 0, status: 'empty' },
      {
        key: 'high',
        label: 'High',
        low_hz: 2500,
        high_hz: 12000,
        value_percent: 0,
        status: 'empty',
      },
      {
        key: 'noise',
        label: 'Noise',
        low_hz: 12000,
        high_hz: 20000,
        value_percent: 0,
        status: 'empty',
      },
    ],
    controls: {
      preview: {
        key: 'preview',
        label: 'Preview',
        enabled: false,
        status: 'waiting-for-reference',
      },
      dry_run: {
        key: 'dry_run',
        label: 'Dry Run',
        enabled: false,
        status: 'waiting-for-reference',
      },
      arm_hardware: {
        key: 'arm_hardware',
        label: 'Arm Hardware',
        enabled: false,
        status: 'locked',
      },
    },
    required_actions: ['load-reference'],
    blocked_actions: ['arm-hardware', 'open-midi-port', 'send-midi', 'record-audio', 'render-gui'],
    safety: {
      passive: true,
      reads_audio_files: false,
      records_audio: false,
      streams_audio: false,
      launches_gui: false,
      opens_ports: false,
      sends_midi: false,
      mutates_hardware: false,
      writes_files: false,
    },
    replay_commands: [
      'python -m rytm_randomizer.cli style-performance-arc-live-gui-analyzer-readiness-report --description <reference-notes> --json',
    ],
  },
  snapshot_history: {
    snapshot_history_version: 'live-gui-snapshot-history-model-v1',
    snapshot_history_id: 'history-test',
    session_label: 'Warehouse arc',
    current_id: 'console-snap-03',
    current_index: 2,
    entry_count: 3,
    entries: [
      {
        key: 'history-03',
        order: 3,
        snapshot_id: 'console-snap-03',
        label: 'Warehouse arc take',
        kind: 'saved',
        via: 'send',
        parent_id: 'console-snap-02',
        device: 'analog_rytm_mk2',
        pad_count: 12,
        scene_slot: 'A01',
        bpm_label: '128 BPM',
        is_current: true,
        is_saved: true,
        can_load: false,
        can_undo_to: false,
        summary: 'current warehouse take',
        test_id: 'snapshot-history-console-snap-03',
      },
    ],
    controls: [],
    safety_lines: ['in-memory only'],
    blocked_actions: ['send MIDI from snapshot history'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-snapshot-history-model-report --json'],
  },
  command_queue: {
    command_queue_version: 'live-gui-command-queue-model-v1',
    command_queue_id: 'queue-test',
    session_label: 'Warehouse arc',
    queue_status: 'pending',
    dry_run_active: true,
    hardware_armed: false,
    active_command_key: null,
    queued_commands: [
      {
        key: 'mutate-pad-11',
        order: 1,
        label: 'Mutate Pad 11',
        status: 'pending',
        enabled: false,
        action_type: 'dry-run',
        target: 'Pad 11 / SY Raw',
        dry_run_only: true,
        estimated_message_count: 28,
        operator_action: 'preview only',
        test_id: 'command-mutate-pad-11',
      },
    ],
    last_actions: [],
    undo_stack: [],
    safety_lines: ['dry-run active'],
    blocked_actions: ['dispatch queued command from model'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-command-queue-model-report --json'],
  },
  safety_checklist: {
    safety_checklist_version: 'live-gui-safety-checklist-model-v1',
    safety_checklist_id: 'safety-test',
    session_label: 'Warehouse arc',
    checklist_status: 'passed',
    passed_count: 4,
    total_count: 4,
    items: [
      {
        key: 'no-midi-port',
        order: 1,
        label: 'No MIDI Port Open',
        status: 'passed',
        severity: 'safe',
        message: 'No hardware port is open.',
        operator_action: 'No action required.',
        test_id: 'safety-no-midi-port',
      },
    ],
    arm_gate: {
      key: 'arm-hardware',
      label: 'Arm Hardware',
      state: 'locked',
      enabled: false,
      reason: 'Hardware arm remains locked in this passive console packet.',
      requirements: ['dry run complete', 'MIDI port open'],
      midi_port_name: null,
      midi_port_open: false,
      hardware_connected: false,
      send_plan_ready: false,
      dry_run_complete: false,
      test_id: 'safety-arm-hardware',
    },
    safety_lines: ['mock safe'],
    blocked_actions: ['arm_hardware'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-safety-checklist-model-report --json'],
  },
  blocked_actions: [
    'open_midi_port_without_arm',
    'a4_outbound_macro_send',
    'dispatch queued command from model',
    'record-audio',
    'send MIDI from snapshot history',
    'MIDI learn or raw CC capture',
    'dispatch Cockpit WebSocket commands',
  ],
  safety_lines: [
    'passive/read-only',
    'no MIDI controller input',
    'no WebSocket command dispatch',
    'no MIDI sending',
    'no port opening',
  ],
  replay_commands: ['python -m rytm_randomizer.cli live-gui-performance-console-report --json'],
};
