import type { LiveGuiPerformanceConsoleModelDict } from '../types/live_gui_protocol';
import { DEFAULT_STYLE_CRATE_REHEARSAL_DECK } from './styleCrateQueueModel';

export const performanceConsoleDemoModel: LiveGuiPerformanceConsoleModelDict = {
  console_version: 'live-gui-performance-console-v1',
  source_module: 'desktop.web.cockpit.performanceConsoleDemoModel',
  console_id: 'console-demo',
  session_label: 'Warehouse arc',
  console_status: 'mock-safe',
  hardware_mode: 'passive',
  device_inventory: {
    model_version: 'live-gui-device-inventory-v1',
    device_count: 2,
    cards: [
      {
        device_id: 'analog_rytm_mk2',
        display_name: 'Elektron Analog Rytm MKII',
        order: 1,
        track_count: 12,
        default_midi_channel_label: '1-12',
        sysex_manufacturer_id_hex: '00 20 3c',
        role_summary: '12-pad drum and sample performance surface',
        port_state: 'closed',
        hardware_state: 'disarmed',
        mock_state: 'mock-safe',
        can_open_port: false,
        can_arm_hardware: false,
        capability_badges: ['12 pads', 'snapshot-safe'],
        passive: true,
      },
      {
        device_id: 'analog_four_mk2',
        display_name: 'Elektron Analog Four MKII',
        order: 2,
        track_count: 4,
        default_midi_channel_label: '1-4',
        sysex_manufacturer_id_hex: '00 20 3c',
        role_summary: '4-track synth performance surface',
        port_state: 'closed',
        hardware_state: 'disarmed',
        mock_state: 'review-only',
        can_open_port: false,
        can_arm_hardware: false,
        capability_badges: ['4 synth tracks', 'macro review'],
        passive: true,
      },
    ],
    blocked_actions: ['open_midi_port_without_arm'],
    safety: ['passive/read-only'],
  },
  rytm_pad_surface: {
    model_version: 'live-gui-12-pad-surface-v1',
    pad_count: 12,
    active_pad_count: 12,
    planned_pad_count: 0,
    cards: Array.from({ length: 12 }, (_, index) => ({
      pad: index + 1,
      track_code: index + 1 === 11 ? 'SY' : `T${index + 1}`,
      label: index + 1 === 11 ? 'SY Raw' : `Pad ${index + 1}`,
      surface_state: 'active',
      ui_enabled: true,
      ui_locked: false,
      lock_reason: '',
      default_role: index + 1 >= 6 && index + 1 <= 8 ? 'tom' : 'performance',
      default_machine_label: index + 1 === 11 ? 'SY Raw' : 'Snapshot machine',
      legal_machine_count: 4,
      snapshot_mutable_machine_count: 4,
      selectable_only_machine_count: 0,
      primary_machine_labels: ['Snapshot machine'],
    })),
    blocked_actions: ['send_midi'],
    safety: ['no MIDI sending'],
  },
  performance_flow: {
    model_version: 'live-gui-performance-flow-model-v1',
    source_module: 'reports.live_gui_performance_flow_model',
    flow_id: 'oxi-rytm-a4-performance-flow',
    flow_status: 'mock-safe',
    current_step_key: 'kit-core',
    steps: [
      {
        key: 'capture-anchor',
        order: 1,
        label: 'Capture Anchor',
        phase: 'setup',
        rytm_command: 'kit / resnapshot',
        analog_four_action: 'soft-capture reference',
        send_policy: 'receive-only',
        recovery_action: 'Z + send',
        status: 'safe',
      },
      {
        key: 'kit-core',
        order: 2,
        label: 'Kit Core',
        phase: 'foundation',
        rytm_command: 'kit-core',
        analog_four_action: 'review warehouse macro',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        status: 'staged',
      },
    ],
    analog_four_readiness: {
      readiness: 'review-ready',
      command: 'python -m rytm_randomizer.cli analog-four-oxi-macro-readiness-report',
      summary: 'A4 macro rows are review-ready; full macro SEND remains blocked.',
      blocked_active_actions: ['a4_outbound_macro_send'],
    },
    analog_four_set_plan: {
      set_name: 'warehouse-arc',
      current_macro: 'home',
      up_next_macros: ['hard-groove', 'dub-pressure', 'industrial-transition'],
      step_count: 4,
      replay_command: 'python -m rytm_randomizer.cli analog-four-oxi-macro-set-planner-report --json',
      summary: 'warehouse-arc stages A4 macro moves for review.',
      blocked_active_actions: ['A4 full macro SEND'],
    },
    blocked_actions: ['a4_outbound_macro_send'],
    safety_lines: ['passive/read-only'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-performance-flow-model-report --json'],
  },
  macro_action_deck: {
    deck_version: 'performance-console-macro-action-deck-v1',
    deck_id: 'rytm-live-macro-actions',
    deck_status: 'passive-ready',
    current_macro_key: 'kit-core',
    cards: [
      {
        macro_key: 'kit-core',
        order: 1,
        label: 'Kit Core',
        shell_command: 'kit-core',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        risk_label: 'safe',
        affected_pads: [1, 2, 3, 4],
        pad_count: 4,
        status: 'staged',
        hardware_action_state: 'blocked',
        hardware_send_enabled: false,
        dry_run_only: true,
        operator_hint: 'Type kit-core in the armed shell, inspect changes, send manually, and recover with home.',
        test_id: 'macro-action-kit-core',
      },
      {
        macro_key: 'hard-groove',
        order: 2,
        label: 'Hard Groove',
        shell_command: 'hard-groove',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        risk_label: 'safe',
        affected_pads: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        pad_count: 11,
        status: 'staged',
        hardware_action_state: 'blocked',
        hardware_send_enabled: false,
        dry_run_only: true,
        operator_hint:
          'Type hard-groove in the armed shell, inspect changes, send manually, and recover with home.',
        test_id: 'macro-action-hard-groove',
      },
      {
        macro_key: 'industrial',
        order: 3,
        label: 'Industrial',
        shell_command: 'industrial',
        send_policy: 'stage-review-send',
        recovery_action: 'home',
        risk_label: 'review',
        affected_pads: [2, 3, 4, 6, 7, 8, 11, 12],
        pad_count: 8,
        status: 'review',
        hardware_action_state: 'blocked',
        hardware_send_enabled: false,
        dry_run_only: true,
        operator_hint:
          'Type industrial in the armed shell, inspect changes, send manually, and recover with home.',
        test_id: 'macro-action-industrial',
      },
    ],
    blocked_actions: ['fire macro from Cockpit console', 'prepare hardware send from Cockpit macro action'],
    safety_lines: [
      'macro action cards are declarative only',
      'operators still use the armed snapshot shell for real sends',
      'all Cockpit macro fire controls stay disabled',
    ],
    replay_commands: [
      'python -m rytm_randomizer.cli oxi-live-macro-catalog-report',
      'python -m rytm_randomizer.cli live-gui-performance-flow-model-report --json',
    ],
  },
  style_queue: DEFAULT_STYLE_CRATE_REHEARSAL_DECK,
  snapshot_history: {
    snapshot_history_version: 'live-gui-snapshot-history-model-v1',
    snapshot_history_id: 'history-test',
    session_label: 'Warehouse arc',
    current_id: 'console-snap-03',
    current_index: 2,
    entry_count: 3,
    entries: [
      {
        key: 'history-03',
        order: 3,
        snapshot_id: 'console-snap-03',
        label: 'Warehouse arc take',
        kind: 'saved',
        via: 'send',
        parent_id: 'console-snap-02',
        device: 'analog_rytm_mk2',
        pad_count: 12,
        scene_slot: 'A01',
        bpm_label: '128 BPM',
        is_current: true,
        is_saved: true,
        can_load: false,
        can_undo_to: false,
        summary: 'current warehouse take',
        test_id: 'snapshot-history-console-snap-03',
      },
    ],
    controls: [],
    safety_lines: ['in-memory only'],
    blocked_actions: ['send MIDI from snapshot history'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-snapshot-history-model-report --json'],
  },
  command_queue: {
    command_queue_version: 'live-gui-command-queue-model-v1',
    command_queue_id: 'queue-test',
    session_label: 'Warehouse arc',
    queue_status: 'pending',
    dry_run_active: true,
    hardware_armed: false,
    active_command_key: null,
    queued_commands: [
      {
        key: 'mutate-pad-11',
        order: 1,
        label: 'Mutate Pad 11',
        status: 'pending',
        enabled: false,
        action_type: 'dry-run',
        target: 'Pad 11 / SY Raw',
        dry_run_only: true,
        estimated_message_count: 28,
        operator_action: 'preview only',
        test_id: 'command-mutate-pad-11',
      },
    ],
    last_actions: [],
    undo_stack: [],
    safety_lines: ['dry-run active'],
    blocked_actions: ['dispatch queued command from model'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-command-queue-model-report --json'],
  },
  safety_checklist: {
    safety_checklist_version: 'live-gui-safety-checklist-model-v1',
    safety_checklist_id: 'safety-test',
    session_label: 'Warehouse arc',
    checklist_status: 'passed',
    passed_count: 4,
    total_count: 4,
    items: [
      {
        key: 'no-midi-port',
        order: 1,
        label: 'No MIDI Port Open',
        status: 'passed',
        severity: 'safe',
        message: 'No hardware port is open.',
        operator_action: 'No action required.',
        test_id: 'safety-no-midi-port',
      },
    ],
    arm_gate: {
      key: 'arm-hardware',
      label: 'Arm Hardware',
      state: 'locked',
      enabled: false,
      reason: 'Hardware arm remains locked in this passive console packet.',
      requirements: ['dry run complete', 'MIDI port open'],
      midi_port_name: null,
      midi_port_open: false,
      hardware_connected: false,
      send_plan_ready: false,
      dry_run_complete: false,
      test_id: 'safety-arm-hardware',
    },
    safety_lines: ['mock safe'],
    blocked_actions: ['arm_hardware'],
    replay_commands: ['python -m rytm_randomizer.cli live-gui-safety-checklist-model-report --json'],
  },
  blocked_actions: [
    'open_midi_port_without_arm',
    'a4_outbound_macro_send',
    'dispatch queued command from model',
    'send MIDI from snapshot history',
  ],
  safety_lines: ['passive/read-only', 'no MIDI sending', 'no port opening'],
  replay_commands: ['python -m rytm_randomizer.cli live-gui-performance-console-report --json'],
};
