/** Production sidecar and retained device fixtures; no hardware backend or sends. */
import { copyFileSync, mkdirSync } from 'node:fs';
import * as path from 'node:path';

import type { Command, ShowBankState } from '../src/ws/protocol';
import { trackConsoleErrors, WS_DIAL_FAILURE } from './fixtures/console_guard';
import { expect, injectTokenLive, primeToken, resolveRepoRoot, test } from './fixtures/wizard_fixture';

test.use({ actionTimeout: 10_000 });

test('original file sources, native scope, named favorite, bank copy and restart stay offline', async ({ page, sidecarControl }, testInfo) => {
  test.setTimeout(120_000);
  const guard = trackConsoleErrors(page, [WS_DIAL_FAILURE]);
  const commands: Command[] = [];
  const states: ShowBankState[] = [];
  page.on('websocket', (socket) => {
    socket.on('framesent', ({ payload }) => {
      const frame = JSON.parse(String(payload)) as { command?: Command };
      if (frame.command) commands.push(frame.command);
    });
    socket.on('framereceived', ({ payload }) => {
      const frame = JSON.parse(String(payload)) as { type?: string; show_bank?: ShowBankState };
      if (frame.type === 'show_bank_changed' && frame.show_bank) states.push(frame.show_bank);
    });
  });
  const repo = resolveRepoRoot();
  const cwd = path.join(sidecarControl.tmpRoot, 'work');
  const captures = path.join(cwd, 'captures');
  mkdirSync(captures, { recursive: true });
  for (const name of ['RYTM_RIO145_AR_CORE_RETURN_Kit.syx', 'A4_RIO145_CORE_RETURN_Kit.syx']) {
    copyFileSync(path.join(repo, 'tests', 'fixtures', 'rio145', name), path.join(captures, name));
  }
  const env = { RYTM_RAND_MIDI_BACKEND: 'off', HOME: sidecarControl.tmpRoot, PYTHONPATH: repo };
  const first = await sidecarControl.start({ env, cwd, onToken: (token) => primeToken(page, token) });
  await page.goto('/');
  const forge = page.getByTestId('show-kit-forge');
  const scope = page.getByTestId('mutation-parameters-panel');
  await expect(page.getByTestId('safety-rail').getByText('Hardware Off')).toBeVisible();
  await page.getByTestId('profile-chips').getByRole('button').first().click();
  await forge.getByLabel('Bank name', { exact: true }).fill('Offline native set');
  await forge.getByRole('button', { name: 'Create show bank', exact: true }).click();
  await expect(forge.getByLabel('Server banks')).not.toHaveValue('');
  await forge.getByRole('button', { name: 'Import captures folder' }).click();
  await forge.getByRole('button', { name: 'Refresh source files' }).click();
  const rytmFile = forge.getByRole('combobox', { name: 'Rytm source file', exact: true });
  const a4File = forge.getByRole('combobox', { name: 'Analog Four source file', exact: true });
  await expect(rytmFile.locator('option')).toHaveCount(2);
  await expect(a4File.locator('option')).toHaveCount(2);
  await rytmFile.selectOption({ index: 1 });
  await a4File.selectOption({ index: 1 });
  await forge.getByRole('button', { name: 'Adopt source files', exact: true }).click();
  await expect(forge.getByRole('heading', { name: 'Forge candidate pairs' })).toBeVisible();
  await scope.getByRole('button', { name: 'Select none', exact: true }).click();
  await scope.getByLabel('Parameter scope device').selectOption('analog_four_mk2');
  await scope.getByRole('button', { name: 'Select none', exact: true }).click();
  await scope.getByLabel('Parameter scope item').selectOption('3');
  await scope.getByLabel('Explicit target track').check();
  await scope.getByRole('tab', { name: 'FILTER', exact: true }).click();
  await scope.getByTestId('parameter-row-3-filter2_resonance').getByRole('checkbox').check();
  await scope.getByTestId('parameter-row-3-Filter1 Frequency').getByRole('checkbox').check();
  await forge.getByLabel('Candidate count').selectOption('1');
  await forge.getByLabel('Starting seed').fill('2026');
  await forge.getByRole('button', { name: /Small/ }).click();
  await forge.getByRole('button', { name: 'Forge 1 candidate pairs', exact: true }).click();
  await expect(forge.getByRole('article', { name: 'Candidate 1', exact: true })).toBeVisible();
  const originalBank = states.at(-1)!.banks.find((bank) => bank.bank_id === states.at(-1)!.active_bank_id)!;
  const original = originalBank.entries[0]!.candidates[0]!;
  expect(original.recipe.a4_algorithm).toBe('native-fields-v1');
  expect(original.recipe.rytm_scope.parameter_cells).toEqual([]);
  expect(original.analog_four_candidate.values.length).toBeGreaterThan(0);
  expect(original.analog_four_candidate.values.every((value) => value.track_id === 3 && ['filter1_frequency', 'filter2_resonance'].includes(value.parameter))).toBe(true);
  expect(original.analog_four_candidate.sysex.retained).not.toBeNull();
  const card = forge.getByRole('article', { name: 'Candidate 1', exact: true });
  await card.getByText('Compare musical changes', { exact: true }).click();
  await expect(card.getByText('No mapped Rytm parameter changes.')).toBeVisible();
  await forge.getByLabel('Starting seed').fill('2027');
  await forge.getByRole('button', { name: /Large/ }).click();
  await forge.getByRole('button', { name: 'Forge 1 candidate pairs', exact: true }).click();
  await expect(forge.getByRole('article', { name: 'Candidate 2', exact: true })).toBeVisible();
  const large = states.at(-1)!.banks[0]!.entries[0]!.candidates[1]!;
  expect(large.recipe.depth_preset).toBe('large');
  expect(large.analog_four_candidate.values.every((value) => value.track_id === 3)).toBe(true);
  await card.getByRole('button', { name: 'Mark favorite', exact: true }).click();
  const metadata = forge.locator('form').filter({ hasText: 'Shape the show moment' });
  await metadata.getByLabel('Name', { exact: true }).fill('Night machine');
  await metadata.getByRole('button', { name: /Save cue/ }).click();
  await expect.poll(() => states.at(-1)?.banks[0]?.entries[0]?.name).toBe('Night machine');
  await forge.getByRole('button', { name: 'Duplicate', exact: true }).click();
  await expect.poll(() => states.at(-1)?.banks[0]?.entries.length).toBe(2);
  const duplicated = states.at(-1)!.banks[0]!.entries[1]!;
  await forge.getByRole('button', { name: `Move ${duplicated.name} earlier`, exact: true }).click();
  await expect.poll(() => states.at(-1)?.banks[0]?.entries[0]?.entry_id).toBe(duplicated.entry_id);
  const orderedIds = states.at(-1)!.banks[0]!.entries.map((entry) => entry.entry_id);
  await forge.getByLabel('Export package ID').fill('native-roundtrip');
  await forge.getByRole('button', { name: 'Export draft local pack', exact: true }).click();
  await expect(forge.getByText(/Exported native-roundtrip/)).toBeVisible();
  await forge.getByLabel('Import package ID').fill('native-roundtrip');
  await forge.getByLabel('New bank ID (optional)').fill('native-roundtrip-copy');
  await forge.getByRole('button', { name: 'Import local pack', exact: true }).click();
  await expect(forge.getByLabel('Server banks')).toHaveValue('native-roundtrip-copy');
  const copy = states.at(-1)!.banks.find((bank) => bank.bank_id === 'native-roundtrip-copy')!;
  expect(copy.entries[0]!.candidates[0]).toEqual(original);
  expect(copy.entries.map((entry) => entry.entry_id)).toEqual(orderedIds);
  expect(copy.entries[0]!.candidates[1]).toEqual(large);
  expect(copy.entries[0]!.selected_candidate_id).toBeNull();
  await forge.getByRole('article', { name: 'Candidate 1', exact: true }).getByRole('button', { name: 'Select for audition' }).click();
  await expect(page.getByTestId('action-send')).toBeDisabled();
  await sidecarControl.stop();
  await sidecarControl.start({ env, cwd, previousToken: first.token, onToken: (token) => injectTokenLive(page, token) });
  await expect(page.getByTestId('safety-rail').getByText('Connected', { exact: true })).toBeVisible({ timeout: 30_000 });
  await forge.getByLabel('Server banks').selectOption('native-roundtrip-copy');
  await forge.getByRole('article', { name: 'Candidate 1', exact: true }).getByRole('button', { name: 'Select for audition' }).click();
  await expect(page.getByTestId('action-send')).toBeDisabled();
  const afterRestart = states.at(-1)!.banks.find((bank) => bank.bank_id === 'native-roundtrip-copy')!;
  expect(afterRestart.entries[0]!.candidates[0]).toEqual(original);
  expect(afterRestart.entries.map((entry) => entry.entry_id)).toEqual(orderedIds);
  await page.setViewportSize({ width: 600, height: 900 });
  await forge.locator('.show-kit-forge-header').scrollIntoViewIfNeeded();
  await expect(forge.getByRole('heading', { name: 'Show Kit Forge', exact: true })).toBeInViewport();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('offline-bank-recalled-narrow.png') });
  expect(commands.some((command) => ['arm', 'send', 'save', 'capture_current_kit', 'list_capture_inputs'].includes(command.type))).toBe(false);
  guard.assertClean();
});
